simpler env

diff --git a/.github/workflows/aws_integration_test.yml b/.github/workflows/aws_integration_test.yml
--- a/.github/workflows/aws_integration_test.yml
+++ b/.github/workflows/aws_integration_test.yml
@@ -40,33 +40,33 @@ jobs:
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v2
 
-      #- name: Build, tag, and push Conformance image to Amazon ECR
-      #  id: build-publish-conformance
-      #  shell: bash
-      #  env:
-      #    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-      #    ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_CONFORMANCE }}
-      #    IMAGE_TAG: latest
-      #  run: |
-      #    docker build -f ./cmd/conformance/aws/Dockerfile . -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
-      #    docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
-      #    echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
-      #    echo "image_tag=$IMAGE_TAG" 
-      #    echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+      - name: Build, tag, and push Conformance image to Amazon ECR
+        id: build-publish-conformance
+        shell: bash
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_CONFORMANCE }}
+          IMAGE_TAG: latest
+        run: |
+          docker build -f ./cmd/conformance/aws/Dockerfile . -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
+          echo "image_tag=$IMAGE_TAG" 
+          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
 
-      #- name: Build, tag, and push Hammer image to Amazon ECR
-      #  id: build-publish-hammer
-      #  shell: bash
-      #  env:
-      #    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-      #    ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_HAMMER }}
-      #    IMAGE_TAG: latest
-      #  run: |
-      #    docker build -f ./internal/hammer/Dockerfile . -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
-      #    docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
-      #    echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
-      #    echo "image_tag=$IMAGE_TAG" 
-      #    echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+      - name: Build, tag, and push Hammer image to Amazon ECR
+        id: build-publish-hammer
+        shell: bash
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_HAMMER }}
+          IMAGE_TAG: latest
+        run: |
+          docker build -f ./internal/hammer/Dockerfile . -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
+          echo "image_tag=$IMAGE_TAG" 
+          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
 
 
       # TODO(phboneff): AuroraDB take a long time to be brouht up and down
@@ -100,32 +100,38 @@ jobs:
           tg_command: "apply"
         env:
           INPUT_POST_EXEC_1: |
-            echo "ecs_cluster=$(terragrunt output -raw ecs_cluster)" >> "$GITHUB_OUTPUT"
+            echo "ECS_CLUSTER=$(terragrunt output -raw ecs_cluster)" >> "$GITHUB_ENV"
           INPUT_POST_EXEC_2: |
-            echo "vpc_subnets=$(terragrunt output -json vpc_subnets)" >> "$GITHUB_OUTPUT"
+            echo "ECS_CLUSTER=$(terragrunt output -json vpc_subnets)" >> "$GITHUB_ENV"
 
       - name: Run Hammer
         id: hammer
         shell: bash
         run: |
-          aws ecs run-task \
+          HAMMER_ARN=$(aws ecs run-task \
             --cluster="$ECS_CLUSTER" \
             --task-definition=hammer \
             --count=1 \
             --launch-type=FARGATE \
             --network-configuration='{"awsvpcConfiguration": {"assignPublicIp":"ENABLED","subnets": '$VPC_SUBNETS'}}' \
-            --query 'tasks[0].taskArn' \
-          > ${{ github.workspace }}/hammer_arn.txt
-          echo "Hammer task running, ARN: $(cat ${{ github.workspace }}/hammer_arn.txt)"
+            --query 'tasks[0].taskArn')
+          echo "Hammer task running, ARN: $HAMMER_ARN"
           echo "Waiting for execution to be done..."
-          aws ecs wait tasks-stopped --cluster="$ECS_CLUSTER" --tasks=[$(cat ${{ github.workspace }}/hammer_arn.txt)]
+          aws ecs wait tasks-stopped --cluster="$ECS_CLUSTER" --tasks=[$HAMMER_ARN]
           echo "Execution done, fetching exit code and returning it"
-          aws ecs describe-tasks --cluster="$ECS_CLUSTER" --tasks=[$(cat ${{ github.workspace }}/hammer_arn.txt)] --query 'tasks[0].containers[0].exitCode' > ${{ github.workspace }}/exit_code.txt 
-          exit $(cat ${{ github.workspace }}/exit_code.txt)
+          exit $(aws ecs describe-tasks --cluster="$ECS_CLUSTER" --tasks=[$HAMMER_ARN] --query 'tasks[0].containers[0].exitCode')
 
-        env:
-          ECS_CLUSTER: ${{ steps.terragrunt-apply.outputs.ecs_cluster }} 
-          VPC_SUBNETS: ${{ steps.terragrunt-apply.outputs.vpc_subnets }} 
+#          echo "Hammer task running, ARN: $(cat ${{ github.workspace }}/hammer_arn.txt)"
+#          echo "Waiting for execution to be done..."
+#          aws ecs wait tasks-stopped --cluster="$ECS_CLUSTER" --tasks=[$(cat ${{ github.workspace }}/hammer_arn.txt)]
+#          echo "Execution done, fetching exit code and returning it"
+#          aws ecs describe-tasks --cluster="$ECS_CLUSTER" --tasks=[$(cat ${{ github.workspace }}/hammer_arn.txt)] --query 'tasks[0].containers[0].exitCode' > ${{ github.workspace }}/exit_code.txt 
+#          exit $(cat ${{ github.workspace }}/exit_code.txt)
+#          > ${{ github.workspace }}/hammer_arn.txt
+
+#        env:
+#          ECS_CLUSTER: ${{ steps.terragrunt-apply.outputs.ecs_cluster }} 
+#          VPC_SUBNETS: ${{ steps.terragrunt-apply.outputs.vpc_subnets }} 
 
       # TODO(phboneff): run conformance test on Fargate
 
